### ISSUE TITLE
Color is deprecated, please switch to Colors

### ISSUE THREAD

**Issue by timholy** [PoisotLab/Brim.jl#13]
See https://github.com/JuliaLang/METADATA.jl/pull/3769; we're about to make Color uninstallable on julia 0.4.

Transition info is [here](https://github.com/JuliaGraphics/Colors.jl#migrating-from-colorjl).

**Comment by tpoisot** [comment]
The `master` branch is using `Colors` already (unless I'm mistaken?) -- but thanks for the heads up.

**Comment by timholy** [comment]
Great. Might need to tag a new release, or deposit a note over at https://github.com/JuliaLang/METADATA.jl/pull/3769 saying you're not concerned.
